### ISSUE TITLE
Submitted to CRAN?

### ISSUE THREAD

**Issue by BradyAJohnston** [jpquast/ggplate#1]
I've identified a bunch of cleanup / improvements that I could put into a pull request. Has this been submitted to CRAN yet? If not I can be speedy about putting it together.

**Comment by jpquast** [comment]
Hi Brady!
Thank you very much for your interest in ggplate! 
I already submitted it to CRAN on Sunday, but you are still very welcome to to create a pull request with improvements!

**Comment by jpquast** [comment]
@BradyAJohnston Actually they asked me to change some things in the DESCRIPTION file so you can still create a pull request with changes before I resubmit.
