### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by stephenrdoyle** [jpquast/ggplate#15]
Hi @jpquast , 

Loving the idea of this package, but having some trouble installing it. Any thoughts on the following error? Running R version 4.0.3.

cheers, 
Steve

* installing *source* package ‘ggplate’ ...
** package ‘ggplate’ successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) :
  /tmp/RtmpAoLLgC/R.INSTALL114d85399294e/ggplate/R/plate_plot.R:219:29: unexpected '>'
218:   # Determine the max number of characters of values
219:   max_label_length <- data |>
                                 ^

**Comment by jpquast** [comment]
Hi @stephenrdoyle,
thanks for posting the issue! This is indeed my fault. The error complains about the base R pipe operator `|>`. I thought it was added in R version 4.0.0 but actually it was only added 4.1.0. So I got the dependency wrong. Is there any chance you can update to at least 4.1.0?

**Comment by stephenrdoyle** [comment]
No worries at all. I have R version 4.1.0 installed and was able to install it successfully. All good!

Many thanks for the quick response. 
Steve
