### ISSUE TITLE
plate direction

### ISSUE THREAD

**Issue by oclaisse** [jpquast/ggplate#4]
Hello, thanks for this new Package. I tried to run it but the output plate is inverted. Line A is below instead of above. I can’t find how to edit, can you help me solve this problem?

**Comment by jpquast** [comment]
Thanks for posting the issue. I have not seen this before while testing. Could you maybe share your input data frame and code that you run. If I can reproduce it I can fix it. 

You can easily turn your input data into code using `dput(mydata)`. Then you can use the `{reprex}` package to post a reproducible example here. Check the **Usage** section of the reprex documentation (https://github.com/tidyverse/reprex)

**Comment by oclaisse** [comment]
Hello, I have run the demo data and attach the ouput 

> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE) 
+ if(nchar(pkg)) library(pkg, character.only=TRUE)}) 
Welcome to ggplate version 0.0.1! 

Have fun plotting your data! 
Message d'avis : 
le package ‘ggplate’ a été compilé avec la version R 4.1.3 
> # Load a dataset of continuous values for a 96-well plate 
> data(data_continuous_96) 
> 
> # Check the structure of the dataset 
> str(data_continuous_96) 
Classes ‘tbl_df’, ‘tbl’ and 'data.frame': 96 obs. of 2 variables: 
$ Value: num 1.19 0.88 0.17 0.85 0.78 0.23 1.95 0.4 0.88 0.26 ... 
$ well : chr "A1" "A2" "A3" "A4" ... 
> # Create a 96-well plot with round wells 
> plate_plot( 
> data = data_continuous_96, 
> position = well, 
> value = Value, 
> plate_size = 96, 
> plate_type = "round" 
> ) 



De: "Jan-Philipp Quast" ***@***.***> 
À: "jpquast/ggplate" ***@***.***> 
Cc: "Olivier Claisse" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 23 Janvier 2023 15:50:36 
Objet: Re: [jpquast/ggplate] plate direction (Issue #4) 





Thanks for posting the issue. I have not seen this before while testing. Could you maybe share your input data frame and code that you run. If I can reproduce it I can fix it. 

You can easily turn your input data into code using dput(mydata) . Then you can use the {reprex} package to post a reproducible example here. Check the Usage section of the reprex documentation ( [ https://github.com/tidyverse/reprex | https://github.com/tidyverse/reprex ] )

**Comment by jpquast** [comment]
For me this produces the following output: 

``` r
library(ggplate)
#> Welcome to ggplate version 0.0.1!
#>                             
#> Have fun plotting your data!

# Load a dataset of continuous values for a 96-well plate
data(data_continuous_96)

# Check the structure of the dataset
str(data_continuous_96)
#> tibble [96 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ Value: num [1:96] 1.19 0.88 0.17 0.85 0.78 0.23 1.95 0.4 0.88 0.26 ...
#>  $ well : chr [1:96] "A1" "A2" "A3" "A4" ...

# Create a 96-well plot with round wells
plate_plot(
  data = data_continuous_96,
  position = well,
  value = Value,
  plate_size = 96,
  plate_type = "round"
)
```

![](https://i.imgur.com/Zk6yWCg.png)

<sup>Created on 2023-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Maybe the issue are outdated R packages or R itself. Maybe try to see if updating packages and R resolves the issue. It could be that the functionality that reverses the axis was introduced in a later version of `{ggplot2}` than what you have installed.
